### ISSUE TITLE
silenceTimeout not work for jest

### ISSUE THREAD

**Issue by luhui** [jfairbank/redux-saga-test-plan#121]
jest version: 18.1.0
use the example for test, it fail with error 
`Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

```js
//mySaga.js

export default function* mySaga() {
  while (true) {
      const action = yield take('READY');
      yield put({ type: 'DATA', payload: action.payload });
  }
}

//test.js
import mySaga from 'sagas/mySaga'

it('can be silenced', () => {
  return expectSaga(mySaga)
    .put({ type: 'DATA', payload: 42 })
    .dispatch({ type: 'READY', payload: 42 })

    // no warning message will be printed
    // this is useful if you expect the saga to time out
    .run({ silenceTimeout: true });
});
```

**Comment by jfairbank** [comment]
Hey, @luhui!

Couple things to note. The `silenceTimeout` only silences the warning that Redux Saga Test Plan cancels your saga if it runs too long. It does not affect the warning that Jest prints if your test takes too long. Please double check the code you're running because that example works fine with no warning messages for me using Jest 18.1.0.

If you're still having issues, can you please create a repo that reproduces this issue? Jest shouldn't be timing out because Redux Saga Test Plan should cancel the saga before the test times out. Also, have you set `jasmine.DEFAULT_TIMEOUT_INTERVAL` to a really small number by chance?

**Comment by luhui** [comment]
Oh, that's my fault, I had make timer as fake in package.json. Just remove this line and it gets pass now

```json
"jest": {
    "timer": "fake"
}
```

**Comment by NickHeiner** [comment]
I can confirm that this issue arises when your test environment mocks `setTimeout`.
