### ISSUE TITLE
Test runs forever (never times out)

### ISSUE THREAD

**Issue by ssynix** [jfairbank/redux-saga-test-plan#127]
I ran into this issue when trying to rewrite my saga tests using this library. What I ran into is that neither `jest`, nor `expectSaga` time out, and the test gets stuck. I don't know whether this is a bug on Jest's end as well, but here's the minimal repro that I finally managed to extract from my app logic:

```typescript
function* endlessSaga() {
    yield takeEvery(ActionCreator, function*() { // If I change ActionCreator to a string pattern, things work
        yield put({ type: 'irrelevant' }); // If I don't yield put, things work
    });
}

it('should time out', () => {
    return expectSaga(endlessSaga)
        .dispatch({ type: 'whatever' })
        .run();
});
```

**Comment by jfairbank** [comment]
Hi, @ssynix!

If `ActionCreator` is returning an action as I'm guessing, then you're probably putting `takeEvery` into an infinite loop. The function pattern for `takeEvery` is meant for inspecting the currently dispatched action in order to determine whether the inner saga should run. If it's automatically returning an action, then it's returning a truthy value every time an action is dispatched, including the inner `yield put({ type: 'irrevelant' })`. For example:

```js
const actionCreator = () => ({ type: 'whatever' });

function* endlessSaga() {
  yield takeEvery(actionCreator, function* () {
    // takeEvery will match here because actionCreator returns truthy value
    // this puts it in an infinite loop
    yield put({ type: 'irrelevant' });
  });
}

it('should time out', () => {
  return expectSaga(endlessSaga)
    // takeEvery will match here because actionCreator returns truthy value
    .dispatch({ type: 'whatever' }) 
    .run();
});
```

Because it's in an infinite loop, it hogs the CPU core and can never be timed out. I'd recommend using the string pattern for `takeEvery`.

Does that make sense?

**Comment by ssynix** [comment]
Ah, I wasn't aware infinite loops can't be timed out (still getting used to asynchronous ≠ multithreaded)

A PR was merged a while back in `redux-saga` which allowed special treatment of certain action creator functions. Note from [API](https://github.com/redux-saga/redux-saga/tree/master/docs/api#takepattern):
>  If the pattern function has toString defined on it, action.type will be tested against pattern.toString() instead. This is useful if you're using an action creator library like redux-act or redux-actions.

I'm assuming you have your own "saga interpreter" instead of directly using `redux-saga`? That could explain the API deviation!

**Comment by jfairbank** [comment]
I use `runSaga` from redux-saga internally, so I don't have a separate interpreter outside of mocking effects if you use providers. If I run the code snippet with `runSaga` directly instead of redux-saga-test-plan, it still loops forever.

You are correct that if the action creator has `toString` defined, then this shouldn't be an issue. But if you're creating an action creator without explicitly defining your own `toString` implementation, then it will still create an infinite loop.

**Comment by ssynix** [comment]
Thanks for the info! I'll have to dig a bit deeper into this.

**Comment by jfairbank** [comment]
No worries! Let me know if you find any issues with redux-saga-test-plan.
