### ISSUE TITLE
How to assert calls are being executed in parallel?

### ISSUE THREAD

**Issue by anguyen1817** [jfairbank/redux-saga-test-plan#174]
Hi,

First, thanks for this amazing library. I have this saga

```
export function* fetchAll() {
  // executing requests in parallel
  yield all([
    call(fetch, 'devices'),
    call(fetch, 'unit')
  ])
}
```

I know I can verify individual call being executed. Is there a way that I can also verify that they are indeed being executed in parallel?

Thanks!

**Comment by jfairbank** [comment]
Hi, @anguyen1817.

You can test this with [`testSaga`'s `all` assertion](http://redux-saga-test-plan.jeremyfairbank.com/unit-testing/effect-creators.html) like this.

```js
import { call } from 'redux-saga/effects'
import { testSaga } from 'redux-saga-test-plan'

it('fetches in parallel', () => {
  testSaga(fetchAll)
    .next()
    .all([
      call(fetch, 'devices'),
      call(fetch, 'unit')
    ])
})
```

You can't test this with `expectSaga`, though, because of some of its implementation details. I'd encourage you to use `expectSaga` more for integration testing behavior than implementation details of your code like what is and isn't parallel. I kind of regret implementing assertions for `fork`, `spawn`, and `race` for this reason.

That being said, I'm not opposed to an `all` assertion's being added to `expectSaga` in the future. It would require some significant changes in the codebase that I unfortunately don't have time to make at the moment. PRs are welcome, though!
