### ISSUE TITLE
Testing Dynamic Values In PUT

### ISSUE THREAD

**Issue by anands** [jfairbank/redux-saga-test-plan#180]
Assuming my saga is as follows:

```js
function* getMessage() {
    // ...
    yield put({
         // ...
         "date" : "Wed Mar 07 2018 14:50:59 GMT+0530 (IST)"
    });
}
```

If date would have been static the basic test would look like:

```js
expectSaga(getMessage)
.put({
   // ...
, date: ...
})
.run()
```
As date is the dynamic value, how can this be tested using the `.put`, can we ignore values? the documentation doesn't speak about this. Appreciate any help.

**Comment by epikhighs** [comment]
I think it depends on what kind of coverage you want from your test.  If the value of the date is really important, then you can mock whatever generates the date.  Otherwise, you can do partial matching (https://redux-saga-test-plan.jeremyfairbank.com/integration-testing/partial-matching.html) and do something like `.put.like({ action: { type: 'FAIL_USER' } })` without specifying the actual payload.

The level of detail in your test depends on your situation and needs.

**Comment by jfairbank** [comment]
@anands Like @epikhighs mentioned you can use partial matching to test only the parts of the action you're interested in. Otherwise, you can mock date generation if you want to verify a date is being added to your action.
