### ISSUE TITLE
Error with Jest

### ISSUE THREAD

**Issue by stefanfrede** [jfairbank/redux-saga-test-plan#217]
I use Jest and if I run a test with redux-saga-test-plan I get the error: `Cannot find module 'redux-saga/lib/internal/sagaHelpers' from 'index.js'`.

I used the most simple example I could find:
```
import { expectSaga } from 'redux-saga-test-plan';

function* saga() {
  return { hello: 'world' };
}

it('returns a greeting', () => {
  return expectSaga(saga)
    .returns({ hello: 'world' })
    .run();
});
```

**Comment by giancarlo88** [comment]
I had the exact same issue. Turns out the latest beta release of redux-saga (`v1.0.0-beta.2`) was to blame, and after downgrading to `v1.0.0-beta.1` the error went away.

You may want to fix the version in `package.json` (remove the `^`) as even though it was a minor release it had a breaking change. 

Should I raise this as a separate issue?

**Comment by stefanfrede** [comment]
I guess if it is not redux-saga-test-plan related I can close the issue.

**Comment by vass-david** [comment]
I had same issue. I've had newest redux-saga v1.1.3 and redux-saga-test-plan v3.7.0. Upgrading redux-saga-test-plan to v4.0.0-rc.3 solved the issue.
