### ISSUE TITLE
Add silentRun to expectSaga api

### ISSUE THREAD

**Issue by jfairbank** [jfairbank/redux-saga-test-plan#87]
Could be a nicer-looking alternative to `run({ silenceTimeout: true })`. It should also take a timeout length as an argument.

```js
.silentRun()    // same as .run({ silenceTimeout: true })
.silentRun(500) // same as .run({ silenceTimeout: true, timeout: 500 })
```

**Comment by prime-ralph** [comment]
I'd really want to try my hand at this. After looking at the source, am I right to assume that I only need to write `.silentRun()`, there are no other parts that need to be updated?

**Comment by jfairbank** [comment]
Hey, @ralphstodomingo! It's all yours.

> After looking at the source, am I right to assume that I only need to write .silentRun(), there are no other parts that need to be updated?

That's correct. You shouldn't need to change anything else in the code. Let me know if you have any questions. Good luck!

**Comment by jfairbank** [comment]
Hi @ralphstodomingo!

I know you had wanted to implement this feature a couple weeks ago. I'm so sorry, but someone has opened up a PR to implement it already! I'm not sure if they saw that you had "claimed" the issue. However, some time had passed before they opened their PR. I suppose it wouldn't be fair to claim an issue and not implement it relatively soon. Regardless, I'm not blaming you or them. I blame myself for not explicitly setting forth contribution guidelines in a document.

I'm still learning how to maintain a repo that others are interested in using, so please forgive me. There are still other [issues](https://github.com/jfairbank/redux-saga-test-plan/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs) that I could use some help on if you like.

I think that going forward I need to add a contributions document that establishes the rules for PRs and whether issues can be claimed or are first-come, first-served. Again, sorry for the mixup, and you're welcome to submit a PR for another open issue if you have the time.

**Comment by ralphstodomingo** [comment]
Yeah, I shouldn't have claimed this so easily like that, and I'm not an experienced contributor in any way. I had the code sitting here for the past week because things came up and I planned to submit it tomorrow. I do agree it was unfair of me to claim it and not have it implemented soon enough. I apologize for any inconvenience it caused.

That being said, I am happy someone else was able to make the PR. I do want to continue supporting this project and will contribute in any way when possible. Thank you guys for all the hard work you put into this project, it makes developing (and testing!) a lot more tolerable and enjoyable.

**Comment by jfairbank** [comment]
No worries, @ralphstodomingo! Sorry you didn't get to implement it, but I appreciate your support and will gladly take more help.
